package analyzer:fundamentals

world analyzer {
  import types

  use types.{fundamental-data, analyzer-output}

  export run: func(company: fundamental-data) -> result<analyzer-output, string>
}

interface types {
    record analyzer-output {
        columns: list<analyzer-output-column>
    }

    record analyzer-output-column {
        name: string,
        value: analyzer-output-column-value,
    }

    variant analyzer-output-column-value {
        v-u32(u32),
        v-f64(float64),
        v-string(string),
        v-bool(bool)
    }

    record activities-involvement {
        activity: option<string>,
        involvement: option<string>,
    }
    record address-data {
        city: option<string>,
        country: option<string>,
        state: option<string>,
        street: option<string>,
        zip: option<string>,
    }
    record analyst-ratings {
        buy: option<s32>,
        hold: option<s32>,
        rating: option<float64>,
        sell: option<s32>,
        strong-buy: option<s32>,
        strong-sell: option<s32>,
        target-price: option<float64>,
    }
    record asset-allocation {
        benchmark: option<string>,
        category-average: option<string>,
        long-percentage: option<string>,
        net-percentage: option<string>,
        short-percentage: option<string>,
        ty: option<string>,
    }
    record asset-allocation-data {
        long-percent: option<float64>,
        net-assets-percent: option<float64>,
        short-percent: option<float64>,
    }
    record asset-allocation-etf {
        bond: option<asset-allocation-data>,
        cash: option<asset-allocation-data>,
        not-classified: option<asset-allocation-data>,
        other: option<asset-allocation-data>,
        stock-us: option<asset-allocation-data>,
        stocknon-us: option<asset-allocation-data>,
    }
    record balance-sheet {
        currency-symbol: option<string>,
        quarterly: list<tuple<string, option<balance-sheet-data>>>,
        quarterly-last-n0: option<balance-sheet-data>,
        quarterly-last-n1: option<balance-sheet-data>,
        quarterly-last-n2: option<balance-sheet-data>,
        quarterly-last-n3: option<balance-sheet-data>,
        yearly: list<tuple<string, option<balance-sheet-data>>>,
        yearly-last-n0: option<balance-sheet-data>,
        yearly-last-n1: option<balance-sheet-data>,
        yearly-last-n2: option<balance-sheet-data>,
        yearly-last-n3: option<balance-sheet-data>,
    }
    record balance-sheet-data {
        accounts-payable: option<float64>,
        accumulated-amortization: option<float64>,
        accumulated-depreciation: option<float64>,
        accumulated-other-comprehensive-income: option<float64>,
        additional-paid-in-capital: option<float64>,
        capital-lease-obligations: option<float64>,
        capital-stock: option<float64>,
        capital-surpluse: option<float64>,
        cash: option<float64>,
        cash-and-equivalents: option<float64>,
        cash-and-short-term-investments: option<float64>,
        common-stock: option<float64>,
        common-stock-shares-outstanding: option<float64>,
        common-stock-total-equity: option<float64>,
        currency-symbol: option<string>,
        current-deferred-revenue: option<float64>,
        deferred-long-term-asset-charges: option<float64>,
        deferred-long-term-liab: option<float64>,
        earning-assets: option<float64>,
        good-will: option<float64>,
        intangible-assets: option<float64>,
        inventory: option<float64>,
        liabilities-and-stockholders-equity: option<float64>,
        long-term-debt: option<float64>,
        long-term-debt-total: option<float64>,
        long-term-investments: option<float64>,
        negative-goodwill: option<float64>,
        net-debt: option<float64>,
        net-invested-capital: option<float64>,
        net-receivables: option<float64>,
        net-tangible-assets: option<float64>,
        net-working-capital: option<float64>,
        non-current-assets-total: option<float64>,
        non-current-liabilities-other: option<float64>,
        non-current-liabilities-total: option<float64>,
        non-currrent-assets-other: option<float64>,
        noncontrolling-interest-in-consolidated-entity: option<float64>,
        other-assets: option<float64>,
        other-current-assets: option<float64>,
        other-current-liab: option<float64>,
        other-liab: option<float64>,
        other-stockholder-equity: option<float64>,
        preferred-stock-redeemable: option<float64>,
        preferred-stock-total-equity: option<float64>,
        property-plant-and-equipment-gross: option<float64>,
        property-plant-and-equipment-net: option<float64>,
        property-plant-equipment: option<float64>,
        retained-earnings: option<float64>,
        retained-earnings-total-equity: option<float64>,
        short-long-term-debt: option<float64>,
        short-long-term-debt-total: option<float64>,
        short-term-debt: option<float64>,
        short-term-investments: option<float64>,
        temporary-equity-redeemable-noncontrolling-interests: option<float64>,
        total-assets: option<float64>,
        total-current-assets: option<float64>,
        total-current-liabilities: option<float64>,
        total-liab: option<float64>,
        total-permanent-equity: option<float64>,
        total-stockholder-equity: option<float64>,
        treasury-stock: option<float64>,
        warrants: option<float64>,
    }
    record cash-flow {
        currency-symbol: option<string>,
        quarterly: list<tuple<string, option<cash-flow-data>>>,
        quarterly-last-n0: option<cash-flow-data>,
        quarterly-last-n1: option<cash-flow-data>,
        quarterly-last-n2: option<cash-flow-data>,
        quarterly-last-n3: option<cash-flow-data>,
        yearly: list<tuple<string, option<cash-flow-data>>>,
        yearly-last-n0: option<cash-flow-data>,
        yearly-last-n1: option<cash-flow-data>,
        yearly-last-n2: option<cash-flow-data>,
        yearly-last-n3: option<cash-flow-data>,
    }
    record cash-flow-data {
        begin-period-cash-flow: option<float64>,
        capital-expenditures: option<float64>,
        cash-and-cash-equivalents-changes: option<float64>,
        cash-flows-other-operating: option<float64>,
        change-in-cash: option<float64>,
        change-in-working-capital: option<float64>,
        change-receivables: option<float64>,
        change-to-account-receivables: option<float64>,
        change-to-inventory: option<float64>,
        change-to-liabilities: option<float64>,
        change-to-netincome: option<float64>,
        change-to-operating-activities: option<float64>,
        currency-symbol: option<string>,
        depreciation: option<float64>,
        dividends-paid: option<float64>,
        end-period-cash-flow: option<float64>,
        exchange-rate-changes: option<float64>,
        free-cash-flow: option<float64>,
        investments: option<float64>,
        net-borrowings: option<float64>,
        net-income: option<float64>,
        other-cashflows-from-financing-activities: option<float64>,
        other-cashflows-from-investing-activities: option<float64>,
        other-non-cash-items: option<float64>,
        sale-purchase-of-stock: option<float64>,
        stock-based-compensation: option<float64>,
        total-cash-from-financing-activities: option<float64>,
        total-cash-from-operating-activities: option<float64>,
        total-cashflows-from-investing-activities: option<float64>,
    }
    record component {
        code: option<string>,
        exchange: option<string>,
        industry: option<string>,
        name: option<string>,
        sector: option<string>,
    }
    record esg-scores {
        activities-involvement: list<tuple<string, option<activities-involvement>>>,
        controversy-level: option<float64>,
        disclaimer: option<string>,
        environment-score: option<float64>,
        environment-score-percentile: option<float64>,
        governance-score: option<float64>,
        governance-score-percentile: option<float64>,
        social-score: option<float64>,
        social-score-percentile: option<float64>,
        total-esg: option<float64>,
        total-esg-percentile: option<float64>,
    }
    record etf-data {
        annual-holdings-turnover: option<float64>,
        asset-allocation: option<asset-allocation-etf>,
        average-mkt-cap-mil: option<float64>,
        company-name: option<string>,
        company-url: option<string>,
        date-ongoing-charge: option<string>,
        dividend-paying-frequency: option<string>,
        domicile: option<string>,
        etf-url: option<string>,
        fixed-income: list<tuple<string, option<fixed-income-data>>>,
        holdings: list<tuple<string, option<holding>>>,
        holdings-count: option<u64>,
        inception-date: option<string>,
        index-name: option<string>,
        isin: option<string>,
        market-capitalisation: option<market-capitalisation-etf>,
        max-annual-mgmt-charge: option<float64>,
        morning-star: option<morning-star>,
        net-expense-ratio: option<float64>,
        ongoing-charge: option<float64>,
        performance: option<performance>,
        sector-weights: option<sector-weight-etf>,
        top-n10-holdings: list<tuple<string, option<holding>>>,
        total-assets: option<float64>,
        valuations-growth: option<valuations-growth>,
        world-regions: option<world-region-etf>,
        yield: option<float64>,
    }
    record earnings {
        annual: list<tuple<string, option<earnings-annual-data>>>,
        history: list<tuple<string, option<earnings-history-data>>>,
        trend: list<tuple<string, option<earnings-trend-data>>>,
    }
    record earnings-annual-data {
        eps-actual: option<float64>,
    }
    record earnings-history-data {
        before-after-market: option<string>,
        currency: option<string>,
        eps-actual: option<float64>,
        eps-difference: option<float64>,
        eps-estimate: option<float64>,
        surprise-percent: option<float64>,
    }
    record earnings-trend-data {
        earnings-estimate-avg: option<float64>,
        earnings-estimate-growth: option<float64>,
        earnings-estimate-high: option<float64>,
        earnings-estimate-low: option<float64>,
        earnings-estimate-number-of-analysts: option<float64>,
        earnings-estimate-year-ago-eps: option<float64>,
        eps-revisions-down-last-n30-days: option<float64>,
        eps-revisions-down-last-n7-days: option<float64>,
        eps-revisions-up-last-n30-days: option<float64>,
        eps-revisions-up-last-n7-days: option<float64>,
        eps-trend-current: option<float64>,
        eps-trend-n30-days-ago: option<float64>,
        eps-trend-n60-days-ago: option<float64>,
        eps-trend-n7-days-ago: option<float64>,
        eps-trend-n90-days-ago: option<float64>,
        growth: option<float64>,
        period: option<string>,
        revenue-estimate-avg: option<float64>,
        revenue-estimate-growth: option<float64>,
        revenue-estimate-high: option<float64>,
        revenue-estimate-low: option<float64>,
        revenue-estimate-number-of-analysts: option<float64>,
        revenue-estimate-year-ago-eps: option<float64>,
    }
    record financials {
        balance-sheet: option<balance-sheet>,
        cash-flow: option<cash-flow>,
        income-statement: option<income-statement>,
    }
    record fixed-income-data {
        fund-percent: option<float64>,
        relative-to-category: option<float64>,
    }
    record fundamental-data {
        analyst-ratings: option<analyst-ratings>,
        components: list<tuple<option<s32>, option<component>>>,
        earnings: option<earnings>,
        esg-scores: option<esg-scores>,
        etf-data: option<etf-data>,
        financials: option<financials>,
        general: option<general>,
        highlights: option<highlights>,
        historical-ticker-components: list<tuple<option<s32>, option<historical-component>>>,
        holders: option<holders>,
        insider-transactions: list<tuple<string, option<insider-transactions>>>,
        mutual-fund-data: option<mutual-fund-data>,
        outstanding-shares: option<outstanding-shares>,
        shares-stats: option<shares-stats>,
        splits-dividends: option<splits-dividends>,
        statistics: option<statistics>,
        technicals: option<technicals>,
        valuation: option<valuation>,
    }
    record general {
        address: option<string>,
        address-data: option<address-data>,
        category: option<string>,
        cik: option<string>,
        code: option<string>,
        country-iso: option<string>,
        country-name: option<string>,
        currency-code: option<string>,
        currency-name: option<string>,
        currency-symbol: option<string>,
        cusip: option<string>,
        description: option<string>,
        employer-id-number: option<string>,
        exchange: option<string>,
        fiscal-year-end: option<string>,
        full-time-employees: option<s32>,
        fund-category: option<string>,
        fund-family: option<string>,
        fund-style: option<string>,
        fund-summary: option<string>,
        gic-group: option<string>,
        gic-industry: option<string>,
        gic-sector: option<string>,
        gic-sub-industry: option<string>,
        home-category: option<string>,
        industry: option<string>,
        international-domestic: option<string>,
        is-delisted: option<bool>,
        isin: option<string>,
        lei: option<string>,
        listings: list<tuple<option<s32>, option<listing>>>,
        logo-url: option<string>,
        market-capitalization: option<float64>,
        name: option<string>,
        officers: list<tuple<option<s32>, option<officer>>>,
        phone: option<string>,
        primary-ticker: option<string>,
        sector: option<string>,
        ty: option<string>,
        web-url: option<string>,
    }
    record growth-rate-data {
        book-value-growth: option<float64>,
        cash-flow-growth: option<float64>,
        historical-earnings-growth: option<float64>,
        long-term-projected-earnings-growth: option<float64>,
        sales-growth: option<float64>,
    }
    record highlights {
        book-value: option<float64>,
        diluted-eps-ttm: option<float64>,
        dividend-share: option<float64>,
        dividend-yield: option<float64>,
        earnings-share: option<float64>,
        ebitda: option<u64>,
        eps-estimate-current-quarter: option<float64>,
        eps-estimate-current-year: option<float64>,
        eps-estimate-next-quarter: option<float64>,
        eps-estimate-next-year: option<float64>,
        gross-profit-ttm: option<u64>,
        market-capitalization: option<float64>,
        market-capitalization-mln: option<float64>,
        operating-margin-ttm: option<float64>,
        pe-ratio: option<float64>,
        peg-ratio: option<float64>,
        profit-margin: option<float64>,
        quarterly-earnings-growth-yoy: option<float64>,
        quarterly-revenue-growth-yoy: option<float64>,
        return-on-assets-ttm: option<float64>,
        return-on-equity-ttm: option<float64>,
        revenue-per-share-ttm: option<float64>,
        revenue-ttm: option<u64>,
        wall-street-target-price: option<float64>,
    }
    record historical-component {
        code: option<string>,
        end-date: option<string>,
        is-active-now: option<s32>,
        is-delisted: option<s32>,
        name: option<string>,
        start-date: option<string>,
    }
    record holders {
        funds: list<tuple<string, option<holders-data>>>,
        institutions: list<tuple<string, option<holders-data>>>,
    }
    record holders-data {
        change: option<u64>,
        change-p: option<float64>,
        current-shares: option<u64>,
        name: option<string>,
        total-assets: option<float64>,
        total-shares: option<float64>,
    }
    record holding {
        assets-percent: option<float64>,
        code: option<string>,
        country: option<string>,
        exchange: option<string>,
        industry: option<string>,
        name: option<string>,
        region: option<string>,
        sector: option<string>,
    }
    record income-statement {
        currency-symbol: option<string>,
        quarterly: list<tuple<string, option<income-statement-data>>>,
        quarterly-last-n0: option<income-statement-data>,
        quarterly-last-n1: option<income-statement-data>,
        quarterly-last-n2: option<income-statement-data>,
        quarterly-last-n3: option<income-statement-data>,
        yearly: list<tuple<string, option<income-statement-data>>>,
        yearly-last-n0: option<income-statement-data>,
        yearly-last-n1: option<income-statement-data>,
        yearly-last-n2: option<income-statement-data>,
        yearly-last-n3: option<income-statement-data>,
    }
    record income-statement-data {
        cost-of-revenue: option<float64>,
        currency-symbol: option<string>,
        depreciation-and-amortization: option<float64>,
        discontinued-operations: option<float64>,
        ebit: option<float64>,
        ebitda: option<float64>,
        effect-of-accounting-charges: option<float64>,
        extraordinary-items: option<float64>,
        gross-profit: option<float64>,
        income-before-tax: option<float64>,
        income-tax-expense: option<float64>,
        interest-expense: option<float64>,
        interest-income: option<float64>,
        minority-interest: option<float64>,
        net-income: option<float64>,
        net-income-applicable-to-common-shares: option<float64>,
        net-income-from-continuing-ops: option<float64>,
        net-interest-income: option<float64>,
        non-operating-income-net-other: option<float64>,
        non-recurring: option<float64>,
        operating-income: option<float64>,
        other-items: option<float64>,
        other-operating-expenses: option<float64>,
        preferred-stock-and-other-adjustments: option<float64>,
        reconciled-depreciation: option<float64>,
        research-development: option<float64>,
        selling-and-marketing-expenses: option<float64>,
        selling-general-administrative: option<float64>,
        tax-provision: option<float64>,
        total-operating-expenses: option<float64>,
        total-other-income-expense-net: option<float64>,
        total-revenue: option<float64>,
    }
    record insider-transactions {
        owner-cik: option<string>,
        owner-name: option<string>,
        post-transaction-amount: option<u64>,
        sec-link: option<string>,
        transaction-acquired-disposed: option<string>,
        transaction-amount: option<u64>,
        transaction-code: option<string>,
        transaction-price: option<float64>,
    }
    record listing {
        code: option<string>,
        exchange: option<string>,
        name: option<string>,
    }
    record market-capitalisation-etf {
        big: option<float64>,
        medium: option<float64>,
        mega: option<float64>,
        micro: option<float64>,
        small: option<float64>,
    }
    record market-capitalization {
        benchmark: option<float64>,
        category-average: option<float64>,
        portfolio-percent: option<float64>,
        size: option<string>,
    }
    record morning-star {
        category-benchmark: option<string>,
        ratio: option<float64>,
        sustainability-ratio: option<float64>,
    }
    record mutual-fund-data {
        asset-allocation: option<string>,
        currency: option<string>,
        domicile: option<string>,
        expense-ratio: option<float64>,
        expense-ratio-date: option<string>,
        fund-category: option<string>,
        fund-style: option<string>,
        inception-date: option<string>,
        market-capitalization: option<string>,
        morning-star-category: option<float64>,
        morning-star-rating: option<float64>,
        morning-star-risk-rating: option<float64>,
        nav: option<float64>,
        portfolio-net-assets: option<float64>,
        prev-close-price: option<float64>,
        sector-weights: option<string>,
        share-class-net-assets: option<float64>,
        top-holdings: list<tuple<option<s32>, option<top-holdings>>>,
        update-date: option<string>,
        value-growth: list<tuple<option<s32>, option<value-growth>>>,
        world-regions: option<string>,
        yield: option<float64>,
        yield-n1-year-ytd: option<float64>,
        yield-n3-year-ytd: option<float64>,
        yield-n5-year-ytd: option<float64>,
        yield-ytd: option<float64>,
    }
    record number-dividends-by-year {
        count: option<s32>,
        year: option<s32>,
    }
    record officer {
        name: option<string>,
        title: option<string>,
        year-born: option<string>,
    }
    record outstanding-shares {
        annual: list<tuple<string, option<outstanding-shares-data>>>,
        quarterly: list<tuple<string, option<outstanding-shares-data>>>,
    }
    record outstanding-shares-data {
        date: option<string>,
        shares: option<float64>,
        shares-mln: option<string>,
    }
    record performance {
        exp-return-n3-y: option<float64>,
        returns-n1-y: option<float64>,
        returns-n10-y: option<float64>,
        returns-n3-y: option<float64>,
        returns-n5-y: option<float64>,
        returns-ytd: option<float64>,
        sharp-ratio-n3-y: option<float64>,
        volatility-n1-y: option<float64>,
        volatility-n3-y: option<float64>,
    }
    record sector-weights {
        amount-percent: option<float64>,
        benchmark: option<float64>,
        category-average: option<float64>,
        ty: option<string>,
    }
    record sector-weight-etf {
        basic-materials: option<world-data>,
        consumer-cyclisials: option<world-data>,
        consumer-defencive: option<world-data>,
        energy: option<world-data>,
        financial-services: option<world-data>,
        healthcare: option<world-data>,
        industrials: option<world-data>,
        technology: option<world-data>,
        utilities: option<world-data>,
    }
    record shares-stats {
        percent-insiders: option<float64>,
        percent-institutions: option<float64>,
        shares-float: option<u64>,
        shares-outstanding: option<u64>,
        shares-short: option<float64>,
        shares-short-prior-month: option<float64>,
        short-percent-float: option<float64>,
        short-percent-outstanding: option<float64>,
        short-ratio: option<float64>,
    }
    record splits-dividends {
        forward-annual-dividend-rate: option<float64>,
        forward-annual-dividend-yield: option<float64>,
        last-split-factor: option<string>,
        number-dividends-by-year: list<tuple<string, option<number-dividends-by-year>>>,
        payout-ratio: option<float64>,
    }
    record statistics {
        circulating-supply: option<u64>,
        explorer: option<string>,
        high-all-time: option<float64>,
        low-all-time: option<float64>,
        market-cap-dominance: option<float64>,
        market-capitalization: option<float64>,
        market-capitalization-diluted: option<float64>,
        message-board: option<string>,
        source-code: option<string>,
        technical-doc: option<string>,
        total-supply: option<u64>,
    }
    record technicals {
        beta: option<float64>,
        day-n200-ma: option<float64>,
        day-n50-ma: option<float64>,
        shares-short: option<u64>,
        shares-short-prior-month: option<u64>,
        short-percent: option<float64>,
        short-ratio: option<float64>,
        week-n52-high: option<float64>,
        week-n52-low: option<float64>,
    }
    record top-holdings {
        change: option<string>,
        name: option<string>,
        owned: option<string>,
        weight: option<float64>,
    }
    record valuation {
        enterprise-value: option<u64>,
        enterprise-value-ebitda: option<float64>,
        enterprise-value-revenue: option<float64>,
        forward-pe: option<float64>,
        price-book-mrq: option<float64>,
        price-sales-ttm: option<float64>,
        trailing-pe: option<float64>,
    }
    record valuations-growth {
        growth-rates-portfolio: option<growth-rate-data>,
        growth-rates-to-category: option<growth-rate-data>,
        valuations-rates-portfolio: option<valuations-rates-data>,
        valuations-rates-to-category: option<valuations-rates-data>,
    }
    record valuations-rates-data {
        dividend-yield-factor: option<float64>,
        price-book: option<float64>,
        price-cash-flow: option<float64>,
        price-prospective-earnings: option<float64>,
        price-sales: option<float64>,
    }
    record value-growth {
        benchmark: option<float64>,
        category-average: option<float64>,
        name: option<string>,
        stock-portfolio: option<float64>,
    }
    record world-region {
        benchmark: option<float64>,
        category-average: option<float64>,
        name: option<string>,
        stocks-percent: option<float64>,
    }
    record world-data {
        equity-percent: option<float64>,
        relative-to-category: option<float64>,
    }
    record world-region-etf {
        africa-middle-east: option<world-data>,
        asia-developed: option<world-data>,
        asia-emerging: option<world-data>,
        australasia: option<world-data>,
        europe-developed: option<world-data>,
        europe-emerging: option<world-data>,
        japan: option<world-data>,
        latin-america: option<world-data>,
        north-america: option<world-data>,
        united-kingdom: option<world-data>,
    }
}
